 - id: filter-client
   dependencies: data-enricher
   stepName: filter clients with bad data
   mainClass: com.company.namespace.FilterClients
   config:
     recordClass: com.company.data.client.laborafax
     conditions:
       condition-1: laborafax.firstName == isEmpty
       condition-2: laborafax.address == isEmpty
       condition-3: laborafax.phone != isNumeric
